### ISSUE TITLE
你好大佬，有几个问题请教下感谢

### ISSUE THREAD

**Issue by kankankankankankan** [vinewx/NanoWrt#3]
1.我配置了Actions，如何让配置后生成到Releases内？
2.有联系方式么可否接受定制？感谢！

**Comment by vinewx** [comment]
- fork本项目
- 删除workflows配置文件中的`if: github.repository == 'vinewx/NanoWrt'`
- 创建secret token并命名为`sec_token`，方法见 -> [文档](https://help.github.com/cn/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)

**Comment by kankankankankankan** [comment]
十分感谢！不知道大佬接定制么

**Comment by vinewx** [comment]
目前没有这方面打算，屏显插件目前功能比较完备：F1 时间 & 年进度条、F2_1 天气信息、F2_2 系统信息、F3 关机。其他插件，fork之后修改 `scripts/extra.sh` 和 `app_config.seed` 即可

**Comment by kankankankankankan** [comment]
感谢回复，我看最近passw**l最近不更新了，可以增加这个https://github.com/jerrykuku/luci-app-vssr
再次感谢热心帮助！
