### ISSUE TITLE
大佬再次请教下两个问题

### ISSUE THREAD

**Issue by kankankankankankan** [vinewx/NanoWrt#4]
1.调整较多，当天二次以上的编译时候就报错了，看内容是名字重复了，怎样将固件只生成到Actions中即可
2.可否给个收款码，请你喝杯咖啡

**Comment by vinewx** [comment]
考虑到Actions附件下载速度不理想，不建议直接上传到Artifacts里。  
至于tag重复引起的错误，可以在你的neo2_friendlywrt.yml文件中`第115行`引入小时和分钟参数，改为：`release_tag="v$(date +%Y%m%d%H%M)_NEO2"`

**Comment by kankankankankankan** [comment]
收到感谢，请赐我一码，一起咖啡

**Comment by kankankankankankan** [comment]
还有个问题想咨询下，想给固件里增加Turbo ACC功能，我增加了下方三个
```
CONFIG_PACKAGE_luci-app-flowoffload=y
CONFIG_PACKAGE_iptables-mod-fullconenat=y
CONFIG_PACKAGE_kmod-ipt-fullconenat=y
```
可以开启里面的DNS及BBR，其他的fullcone nat都不能打开，不知道有什么办法可以实现？
再次谢谢啦！

**Comment by vinewx** [comment]
friendlywrt官方内核不支持`FlowOffload`

**Comment by kankankankankankan** [comment]
收到 感谢解答
