### ISSUE TITLE
哈喽大佬 感谢您的分享

### ISSUE THREAD

**Issue by kankankankankankan** [vinewx/NanoWrt#5]
自己也摸索了下，增加passwall、shadow*-plus 但因技术有限确实不能编译，次次失败，可否增加下这两个插件
再次感谢！

**Comment by vinewx** [comment]
官方源码缺少依赖包，golang包也有问题，可以尝试使用L大的源码编译：
1. 第61行替换为：`git clone https://github.com/coolsnowwolf/lede openwrt`
2. 注释第73、77、78行

**Comment by kankankankankankan** [comment]
👍🏻 感谢明示~ 我尝试下
